config/routes.rb
Rssdemonexportwebapp::Application.routes.draw do
  devise_for :admins, :skip => :registrations
  resources :uploads, only: [:new, :create, :show]

  root "static_pages#home", via: 'get'

  match '/feedbackpos',      to:     'uploads#yes', via: 'get'
  match '/feedbackneg',      to:     'uploads#no', via: 'get'

  unauthenticated do
      match '/stats',        to:     'static_pages#home',   via: 'get'
  end

  authenticated do
      match '/stats',        to:     'static_pages#stats',   via: 'get'
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:trackable, :lockable
end

app/models/ahoy/event.rb
module Ahoy
  class Event < ActiveRecord::Base
    self.table_name = "ahoy_events"

    belongs_to :visit
    belongs_to :user
  end
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	has_attached_file :database
	#do_not_validate_attachment_file_type :database
	validates_attachment_content_type :database, :content_type => ["application/octet-stream"]
	validates_attachment_file_name :database, :matches => [/db\Z/]
	
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
require 'upload'

class StaticPagesController < ApplicationController
  def home
    @upload = Upload.new
  end

  def stats
    @visits = Visit.all
    @events = Ahoy::Event.all
    @event_counts = Ahoy::Event.group(:name).count
    @exports = Ahoy::Event.where(name: "export complete").map(&:properties)
  end
end

app/controllers/uploads_controller.rb
require 'uploads_helper'
require 'addressable/uri'

class UploadsController < ApplicationController
  rescue_from ActionController::ParameterMissing, with: :empty_file_select

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.create(user_params)
     if @upload.save
        redirect_to @upload#, notice: 'upload was successfully created.'
     else
	render 'new'
     end
  end

  def show
    @upload = Upload.find(params[:id])
    uri = Addressable::URI.parse @upload.database.url
    ahoy.track("try export", {"uri" => uri.path})
    @exportfile = UploadsHelper.runexport(uri.path, ahoy)
  end

  def yes
    ahoy.track("sucessful export")
    render text: 'Feedback received', content_type: 'text/plain'
  end

  def no
    ahoy.track("failed export")
    render text: 'Neg Feedback received', content_type: 'text/plain'
  end

  def user_params
    params.require(:upload).permit(:database)
  end

  private

  def empty_file_select
    @upload = Upload.new
    render 'new'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcast.rb
class Podcast
  attr_reader :title, :htmlurl, :url, :type

  def initialize title, htmlurl, url, type
    @title = title
    @htmlurl = htmlurl
    @url = url
    @type = type
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
# Script to generate OPML of podcasts from RSSDemon
#
# Thanks to
# https://github.com/eddsteel/banshee-podcast-opml and
# http://blog.slashpoundbang.com/post/3385815540/how-to-generate-an-opml-file-with-ruby
#
# Public domain.

require 'rubygems'
require 'builder'
require 'sqlite3'
require 'podcast'
require 'ahoy_matey'
require 'rufus-scheduler'
require 'securerandom'

USER = 'username'
EMAIL = 'user@domain.de'
#DB_FILE = "#{ENV['HOME']}/download/github/banshee-podcast-opml/Database.db"

def UploadsHelper.runexport(dbfilename, ahoy)

Rails.logger.debug "filename: " + dbfilename

podcasts = []
db = SQLite3::Database.new("public" + dbfilename)
db.execute 'select * from Feed ' do |row|
  podcasts << Podcast.new(row[6], row[9], row[4], row[3])
end

exportpath = File.dirname(dbfilename)
file = "result-" + SecureRandom.urlsafe_base64(8) + ".opml"
exportfilename = File.join(exportpath, file)
f = File.new("public" +  exportfilename, "w")  

xml = Builder::XmlMarkup.new(:target => f, :indent => 2)
xml.instruct!
xml.opml(:version => 1.1) do
  xml.head do
    xml.title 'Podcasts'
    xml.dateCreated Time.new.httpdate
    xml.dateModified Time.now.httpdate
    xml.ownerName USER
    xml.ownerEmail EMAIL
  end
  xml.body do
    podcasts.each do |podcast|
      title = podcast.title
      xml.outline(:type => podcast.type, :version => 'RSS', 
                  :description => "",
                  :title => title, :text => title, 
                   :xmlUrl => podcast.url,
		   :htmlUrl => podcast.htmlurl)
      xml.text! "\n"

    end
  end
end

f.close()
ahoy.track("completed export", {"name" => dbfilename, "feedcount" => podcasts.count})

scheduler = Rufus::Scheduler.new

scheduler.in '30m' do
  File.delete(File.join("public", exportfilename))
  File.delete(File.join("public", dbfilename))
end


exportfilename

end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Export feeds and articles from RssDemon to OPML</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
      <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
        </script>
      <![endif]-->
</head>
<body>
    <header class="navbar navbar-fixed-top">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav pull-right">
            <!-- <li><%= link_to "Home",   '/' %></li> -->
            <!-- <li><%= link_to "Help",   '#' %></li> -->
          </ul>
        </nav>
      </div>
    </header>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><i class="fa fa-warning"></i> <%= msg %></li>
    <% end %>
    </ul>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<script>
  ahoy.trackAll();
</script>

<div class="jumbotron">

  <!-- <h2><i class="fa fa-rss"></i> Export feeds and articles from RssDemon Android-App to OPML</h2> -->
<h2><%= image_tag("rss.png", size: "40") %></i> Export feeds from RssDemon Android-App to OPML</h2>
<p>Development for the RssDemon App is not continued anymore. Unfortunately the export feature that the app is supposed 
	to have does not work. Thus when you would like to switch to another RSS App you have to re-enter all your feeds by hand.</p>

<h3>But wait. There is hope:</h3>
<p>With the help of this website it is possible to extract all your data from RssDemon into OPML format. And then you can import it into any other RSS Reader that supports OPML. Here is how:</p>

<ol>
	<li>Find your Database.db from RssDemon</li>
	<li>Upload it here</li>
	<li>Download your exported feeds in an OPML file</li>	
</ol>
<br />
	<div class="col-md-12"><div class="text-center">
	<%= link_to new_upload_path do %>
		<span class="btn btn-primary btn-lg">Alright. Let's do it!</span>
	<% end %>
 	</div></div>

<br />
<br />
</div>

app/views/static_pages/stats.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<h1>Statistics for RSSDemonExport</h1>

<h3>Overall numbers</h3>
Visits: <%= @visits.count %><br />
PIs:  <%= @event_counts["$view"] %><br />
Exports: <%= @event_counts["export complete"] %>

<h3>Visits per day</h3>
<%= line_chart @visits.group_by_day(:started_at).count %>

<h3>Number of events</h3>
<%= column_chart @event_counts %>

<h3>Log of sucessful exports</h3>
<table>
  <tr> <th>Filename</th><th>Number of Feeds</th> </tr>
  <% @exports.each do |export|  %>
    <tr>
      <td><%= export["name"] %></td>
      <td style="text-align:right"><%= export["feedcount"]  %></td>
    </tr>
  <% end %>
</table>

app/views/uploads/new.html.erb
<script>
  ahoy.trackAll();
</script>

<div class="jumbotron">
  <h2><%= image_tag("rss.png", size: "40") %></i> Export feeds from RssDemon Android-App to OPML</h2>
<ol>
	<li><b>Find your Database.db from RssDemon</b>
		<p>Start the "MyFiles" App or any other filemanager (I recommend ES File Explorer). And look on the
		device storage (sdcard) for a folder called "com.meecel.rssdemon". In that folder you will find the Database.db file</p>
		<p>It might be a path like:<br />
		/sdcard/com.meecel.rssdemon/<br />
		/extSdCard/com.meecel.rssdemon<br /></p>
	</li>
	<li><b>Upload it here</b><br />
	<div style="width:75%; padding:1em 2em;">
		<%= form_for @upload, :url => uploads_path, :html => { :multipart => true } do |form| %>
      			 <%= render 'shared/error_messages', object: form.object %>

			  <div style="float:left">
			  <%= form.file_field :database, class: 'btn btn-default' %>
        		 </div>
			  <div style="float:right">
			  <button class='btn btn-primary'>
			    <!--<i class="fa fa-upload"></i>&nbsp;-->Upload
			  </button>
        		 </div>
		  <% end %>
        </div>
	<br />
	</li style="clear:both">
	<li><b>Download your OPML</b></li>	
</ol>
	

</div>

app/views/uploads/show.html.erb
<script>
  ahoy.trackAll();
</script>
 
 <div class="jumbotron">
   <h2><%= image_tag("rss.png", size: "40") %></i> Export feeds from RssDemon Android-App to OPML</h2>
<p class=" alert alert-success">Successfully uploaded the file</p>

<div class="col-md-12"><div class="text-center">
  <%= link_to @exportfile do %>
	<span class="btn btn-primary btn-lg">Download the OPML file</span>
  <% end %>
</div></div>
<br />
<br />

</div>

 <div class="text-center jumbotron">
   <h4>Did it work?</h4>
   <div>
     <%= link_to "/feedbackpos", remote: true, id: 'send_pos_feedback' do %>
         <span class="btn btn-primary">Yes</span>
     <% end %>
     <%= link_to "/feedbackneg", remote: true do %>
         <span class="btn btn-primary">No</span>
     <% end %>
  </div>
  If it didn't work send me an <%= mail_to "ichmagfisch@googlemail.com", "email", subject: "Export feeds from RssDemon didn't work" %>

</div>